### ISSUE TITLE
Add mention of SwiftFriendlyId (compatible library in Swift)

### ISSUE THREAD

**Issue by kdubb** [Devskiller/friendly-id#12]
We use this library in our server code quite a bit and it's great!  The time has come where we need to encode ids on the client in some cases so I created a replica in Swift... [SwiftFrieldlyId](https://github.com/kdubb/SwiftFriendlyId).

Thought I'd mention it since I looked around a bit before replicating the library myself.  Links to implementations in other languages might others quite a bit.

**Comment by mariuszs** [comment]
Done!
