### ISSUE TITLE
Problem with ID deserialization with Spring Boot 1.5.10

### ISSUE THREAD

**Issue by jkubrynski** [Devskiller/friendly-id#5]
After upgrading to Spring Boot 1.5.10 the following exception is thrown after sending classic UUID field:

`com.fasterxml.jackson.databind.JsonMappingException: String 'ec56d1c6-878e-4dcb-975d-1d8f1c124be0' contains illegal characters, only '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' are allowed`

**Comment by mariuszs** [comment]
Try this workaround https://github.com/Devskiller/friendly-id/commit/e5351ae716c3f1e5b845b419b80332ad3fc9756f
