### ISSUE TITLE
Is friendly-id supposed to be compatible with Dropwizard?

### ISSUE THREAD

**Issue by mattcree** [Devskiller/friendly-id#6]
I see that the project is designed to work with Spring Boot, but I am currently working on a Dropwizard app -- the IDs from my project are successfully serialized by friendly-id in the responses -- however, when I'm doing a GET request using a @PathParam UUID, I'm giving the Url62 encoded ID and I get 404s presumably because friendly-id is not having its chance to deserialize the PathParam?

Would you have a any idea why this is? I've read a bit about PathParams being handled by Jersey rather than Jackson deserialization. Presumably this means that the Dropwizard app is simply discarding the request because it isn't finding a UUID as the PathParam. I've tried writing a custom ParamConverter but even that didn't work. I was reading around that these seem to be designed to work with QueryParam and FormParam but not PathParam.

I wish I was writing erlang again.

My resource looks like this;

```
    public void thingDoer(@NotNull @PathParam("id") @ApiParam(required = true) UUID id,
                                        @Suspended AsyncResponse asyncResponse) {
        service.getStuff(id).subscribe(
                success -> asyncResponse.resume(ok(success)),
                error -> asyncResponse.resume(responseForError(error))
        );
    }
```

Any information or guidance would be appreciated.

**Comment by mariuszs** [comment]
Hi, could you provide some small sample project with this issue? I'm not familiar with Dropwizard.

**Comment by mariuszs** [comment]
Could you check this converter with dropwizard?

https://gist.github.com/mariuszs/4ae5f8a88351930e47635921ca9b6f41

**Comment by mariuszs** [comment]
closed due to lack of activity, feel free to reopen if needed
